services:
  webhook-app:
    image: ghcr.io/kaystar-nj4/turbo-chatwoot-webhook:latest
    container_name: turbo-chatwoot-webhook
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=webhook-postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-chatwoot_webhook}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - REDIS_HOST=webhook-redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - webhook-postgres
      - webhook-redis
    networks:
      - docker_default
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/webhook/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webhook-postgres:
    image: postgres:16-alpine
    container_name: webhook-postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-chatwoot_webhook}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    networks:
      - docker_default

  webhook-redis:
    image: redis:7-alpine
    container_name: webhook-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - docker_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data:

networks:
  docker_default:
    external: true
