version: '3.8'

services:
  # Development application with hot reload
  webhook-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turbo-chatwoot-webhook-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REPOSITORY_TYPE=${REPOSITORY_TYPE:-redis}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      redis-dev:
        condition: service_healthy
    networks:
      - webhook-dev-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/webhook/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: webhook-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - webhook-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # PostgreSQL for development (optional)
  postgres-dev:
    image: postgres:15-alpine
    container_name: webhook-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-chatwoot_webhook_dev}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - webhook-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-chatwoot_webhook_dev}"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - postgresql

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: webhook-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - webhook-dev-network
    profiles:
      - mailhog

volumes:
  redis_dev_data:
  postgres_dev_data:

networks:
  webhook-dev-network:
    driver: bridge