services:
  turbo-webhook-app:
    image: ghcr.io/kaystar-nj4/turbo-chatwoot-webhook:latest
    container_name: turbo-webhook-app
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - turbo-webhook-postgres
      - turbo-webhook-redis
    networks:
      - docker_default
    command: sh -c "sleep 10 && yarn migrate && yarn seed && yarn start"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/webhook/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  turbo-webhook-postgres:
    image: postgres:16-alpine
    container_name: turbo-webhook-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - docker_default

  turbo-webhook-redis:
    image: redis:7-alpine
    container_name: turbo-webhook-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - docker_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data:

networks:
  docker_default:
    external: true

